### ISSUE TITLE
Not PHP 5.4 compatible - "session_unregister"

### ISSUE THREAD

**Issue by farfallosa** [phpcollab/v2.x#12]
"session_unregister" used in projects_site/home.php is not working in PHP 5.4 any more

**Comment by mindblender** [comment]
Hi Farfallosa, I believe I have fixed that issue on the 5.x branch.  If you could, please checkout a copy of that branch and give it a try.  I'd appreciate any feedback on any other issues you might have under 5.4

Thanks!

**Comment by farfallosa** [comment]
Hi Mindblender, thanks for the fix. But what does not work is notifying clients with links (exact path) to tasks or discussions. It only links to the project. This way clients would have to check themselves where to find the new discussion or task/ subtask. 
Is there a way to fix this, too? Would appreciate this very much. 
Thanks in advance. Regards!

**Comment by mindblender** [comment]
Ok thanks.  I'll try and take a look at it this week.

Btw, did you apply the php5.x branch to your code?  If so, any problems that you found with the new changes?

**Comment by mindblender** [comment]
Hi Farfallosa, It appears that this is a logic issue in the code and not a PHP version issue.   I will not be fixing issues like this in v2.x.  But I will be sure that they are addressed in v3.

If you are getting an error when the task/discussion is added, please let me know what that error is.

Thanks!

**Comment by farfallosa** [comment]
Hi Mindblender, thanks for your support. May be the problem is cause by security management and handling Seccion IDs. So we'll wait for V3.x. 
There is no error message. The link to the special task or discussion topic that was changed or posted is just cut and addresses the project home while being called out of notifications.

After I used the fixes of php5.x branch another bug came up: When receiving the notification and clicking the link I get the message, that i am not authorized  - although I am the admin. 

Thanks and lets hope that V3 will come this year ;-)

**Comment by mindblender** [comment]
Hmm interesting.  I'll take another look, maybe I missed something.  Could you forward me an example of the email or paste it here for me to look at?  Just want to make sure I'm looking at the same thing :)

**Comment by farfallosa** [comment]
It was just a message at the webpage. I have no copy. I undid the changes. I only kept projects_site/home.php. The client now is able to login client-side and other functions on team-side keep still working.

**Comment by mindblender** [comment]
Just curious, any particular reason why you undid the changes from the 5.x branch?

**Comment by farfallosa** [comment]
I could not identify the files of the 5x branch which caused the problems mentioned above. So I replaced them again, to get a working solution for mostly used functions. But I scheduled a closer check and than I will replace the files again with those out of the 5x branch. Thanks.

**Comment by mindblender** [comment]
Thanks for the feedback.  I'd be curious if the 5.x branch caused you any problem.  If so, please let me know so I can fix them.
